org.gradle.jvmargs             = -Xmx4G
org.gradle.parallel            = true
org.gradle.configuration-cache = false

# Fabric
minecraft_version              = 26.2
loader_version                 = 0.19.5
loom_version                   = 1.17-SNAPSHOT
fabric_version                 = 0.160.0+26.2

# Mod
mod_version                    = 2.3.0
maven_group                    = com.klinbee.moredensityfunctions
archives_base_name             = moredensityfunctions-fabric
